-- 상품을 구매한 회원 비율 구하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/131534
SELECT
    YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT O.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT O.USER_ID) / T.C, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE O
    INNER JOIN USER_INFO U ON U.USER_ID = O.USER_ID
    INNER JOIN (SELECT COUNT(USER_ID) AS C FROM USER_INFO WHERE YEAR(JOINED) = '2021') AS T ON TRUE
WHERE YEAR(JOINED)='2021'
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH