-- 보호소에서 중성화한 동물
-- https://school.programmers.co.kr/learn/courses/30/lessons/59045
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS AS I RIGHT JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID=O.ANIMAL_ID
WHERE (I.SEX_UPON_INTAKE NOT LIKE 'Spayed%' AND I.SEX_UPON_INTAKE NOT LIKE 'Neutered%')
  AND (O.SEX_UPON_OUTCOME LIKE 'Spayed%' OR O.SEX_UPON_OUTCOME LIKE 'Neutered%')
ORDER BY I.ANIMAL_ID

-- 식품분류별 가장 비싼 식품의 정보 조회하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/131116
SELECT P.CATEGORY, T.MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT AS P
         RIGHT JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) AS T
                    ON P.CATEGORY=T.CATEGORY AND P.PRICE=T.MAX_PRICE
ORDER BY T.MAX_PRICE DESC



SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (P.PRICE * O.TOTAL_AMOUNT) AS TOTAL_SALES FROM FOOD_PRODUCT AS P
JOIN
    (
        SELECT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT FROM FOOD_ORDER
        WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m')='2022-05'
        GROUP BY PRODUCT_ID
    ) AS O
ON P.PRODUCT_ID=O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID